version: '3.8'

services:
  app:
    # Build the image from the Dockerfile in the current directory
    build: .
    # Map port 3000 on the host to port 3000 in the container
    ports:
      - "3000:3000"
    # Mount a volume to persist the SQLite database
    # This links the './data' directory on your machine to the '/app/src/data' directory in the container
    volumes:
      - ./data:/app/src/data
    environment:
      - DOCKER_ENV=true
